"""empty message

Revision ID: 5c2ac865a2cb
Revises: 1b3d9a238498
Create Date: 2026-01-13 00:34:49.975246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c2ac865a2cb'
down_revision = '1b3d9a238498'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_type', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('target_id', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_column('target_id')
        batch_op.drop_column('target_type')

    # ### end Alembic commands ###
