"""empty message

Revision ID: 5e60152a008f
Revises: 5c2ac865a2cb
Create Date: 2026-01-13 23:34:16.266331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e60152a008f'
down_revision = '5c2ac865a2cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        # batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('place_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('place_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('p', 'places', ['place_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
